using Content.Goobstation.Shared.JoinQueue;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing; // Arcane-edit

namespace Content.Goobstation.Client.JoinQueue;

[GenerateTypedNameReferences]
public sealed partial class QueueGui : Control
{
    private const float SidePanelsMinWidth = 1360f; // Arcane-edit

    public event Action? QuitPressed;


    public QueueGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        QuitButton.OnPressed += _ => QuitPressed?.Invoke();
    }

    // Arcane-edit-start
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var showSidePanels = Size.X >= SidePanelsMinWidth;
        MiniGameLeaderboardPanel.Visible = showSidePanels;
        QueueTimeLeaderboardPanel.Visible = showSidePanels;
    }
    // Arcane-edit-end

    public void UpdateInfo(QueueUpdateMessage msg)
    {
        QueueTotal.Text = msg.Total.ToString();
        QueuePosition.Text = msg.Position.ToString();
        PatronPanel.Visible = msg.IsPatron;

        if (msg.EstimatedWaitSeconds >= 0)
        {
            var minutes = (int)(msg.EstimatedWaitSeconds / 60);
            EstimatedWait.Text = minutes < 1
                ? Loc.GetString("queue-estimated-wait-soon")
                : Loc.GetString("queue-estimated-wait", ("minutes", minutes));
        }
        else
        {
            EstimatedWait.Text = Loc.GetString("queue-estimated-wait-unknown");
        }

        ServerInfo.Text = Loc.GetString("queue-server-info",
            ("map", msg.MapName),
            ("mode", msg.GameMode),
            ("players", msg.ServerPlayerCount),
            ("max", msg.MaxPlayerCount),
            ("duration", msg.RoundDurationMinutes));

        CritterWalk.UpdateCritters(msg.PlayerNames, msg.YourName);
        // Arcane-edit-start
        MiniGameLeaderboard.UpdateGameLeaderboard(msg.MiniGameLeaderboard);
        QueueTimeLeaderboard.UpdateQueuePlayers(msg.PlayerNames, msg.PlayerWaitSeconds, msg.YourName);
        // Arcane-edit-end
    }
}
