using Content.Shared._Arcane.ERP.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client._Arcane.ERP.UI;

[GenerateTypedNameReferences]
public sealed partial class ErpPreferencesTab : BoxContainer
{
    // Variants available per organ slot
    private static readonly Dictionary<string, string[]> OrganVariants = new()
    {
        [ErpOrganSlots.Penis]      = ["human", "knotted", "equine", "canine", "barbknot", "tapered"],
        [ErpOrganSlots.Vagina]     = ["human", "gaping", "tentacle", "dentata", "hairy", "furred"],
        [ErpOrganSlots.Breasts]    = ["pair_a", "pair_b", "pair_c", "pair_d", "pair_e", "pair_f", "pair_g", "pair_h"],
        [ErpOrganSlots.Testicles]  = ["single", "hidden"],
        [ErpOrganSlots.Anus]       = ["donut", "squished"],
    };

    // Slots where the variant already encodes size — no separate size slider needed
    private static readonly HashSet<string> SlotsWithoutSize =
    [
        ErpOrganSlots.Breasts,
        ErpOrganSlots.Testicles,
    ];

    private ErpOrganPreferences _prefs = ErpOrganPreferences.Default();

    // Per-organ controls (Size and SizeLabel are null for SlotsWithoutSize)
    private readonly Dictionary<string, (OptionButton Variant, Slider? Size, Label? SizeLabel)> _organControls = new();

    public event Action<ErpOrganPreferences>? OnPreferencesChanged;

    public ErpPreferencesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BuildOrganRows();
    }

    private void BuildOrganRows()
    {
        foreach (var slotId in ErpOrganSlots.All)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true, SeparationOverride = 6 };

            var label = new Label
            {
                Text = Loc.GetString($"erp-preferences-tab-organ-{slotId}"),
                MinWidth = 100,
                VAlign = Label.VAlignMode.Center,
            };

            var variantBtn = new OptionButton { MinWidth = 110 };
            var variants = OrganVariants.TryGetValue(slotId, out var v) ? v : ["human"];
            foreach (var variant in variants)
                variantBtn.AddItem(Loc.GetString($"erp-preferences-tab-variant-{variant}"), variantBtn.ItemCount);

            variantBtn.OnItemSelected += args =>
            {
                variantBtn.SelectId(args.Id);
                UpdateOrganConfig(slotId);
            };

            row.AddChild(label);
            row.AddChild(variantBtn);

            Slider? sizeSlider = null;
            Label? sizeLabel = null;

            if (!SlotsWithoutSize.Contains(slotId))
            {
                sizeLabel = new Label { MinWidth = 30, VAlign = Label.VAlignMode.Center };
                sizeSlider = new Slider
                {
                    MinValue = 1,
                    MaxValue = 8,
                    HorizontalExpand = true,
                    Margin = new Thickness(4, 0),
                };

                sizeSlider.OnValueChanged += _ =>
                {
                    sizeLabel.Text = ((int) sizeSlider.Value).ToString();
                    UpdateOrganConfig(slotId);
                };

                row.AddChild(sizeSlider);
                row.AddChild(sizeLabel);
            }

            OrgansContainer.AddChild(row);
            _organControls[slotId] = (variantBtn, sizeSlider, sizeLabel);
        }
    }

    private void UpdateOrganConfig(string slotId)
    {
        if (!_organControls.TryGetValue(slotId, out var controls))
            return;

        var variants = OrganVariants.TryGetValue(slotId, out var v) ? v : ["human"];
        var variantIdx = controls.Variant.SelectedId;
        var variant = variantIdx < variants.Length ? variants[variantIdx] : "human";
        // For slots without a size slider, size is derived from variant index (1-based)
        var size = controls.Size != null ? (int) Math.Round(controls.Size.Value) : variantIdx + 1;

        _prefs.SetOrgan(slotId, new ErpOrganConfig { Variant = variant, Size = size });
        OnPreferencesChanged?.Invoke(_prefs);
    }

    public void SetPreferences(ErpOrganPreferences prefs)
    {
        _prefs = prefs;

        foreach (var slotId in ErpOrganSlots.All)
        {
            if (!_organControls.TryGetValue(slotId, out var controls))
                continue;

            var cfg = prefs.GetOrgan(slotId);

            var variants = OrganVariants.TryGetValue(slotId, out var v) ? v : ["human"];
            var variantIdx = Array.IndexOf(variants, cfg.Variant);
            controls.Variant.SelectId(variantIdx >= 0 ? variantIdx : 0);

            if (controls.Size != null && controls.SizeLabel != null)
            {
                controls.Size.Value = Math.Clamp(cfg.Size, 1, 8);
                controls.SizeLabel.Text = cfg.Size.ToString();
            }
        }
    }

}
